title: Home made resturant
author: Antonyo fernando
email: antonyo@domain.com
description: > # this means to ignore newlines until "baseurl:"
  your favourit food are deliverd quik and esily. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
